config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :tweets, only: [:create] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  validates :body, length: {minimum: 1, maximum: 280}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index 
  end 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new
  end 

  def create
    tweet = Tweet.new(tweet_params.merge(user: current_user))

    if tweet.save 
      redirect_to root_path 
    end
  end 

  private 
  def tweet_params 
    params.require(:tweet).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <!-- blank -->
  <%= link_to 'Log out', destroy_user_session_path, data: {"turbo-method": :delete}, class: 'btn btn-danger' %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  <%= link_to 'Log in', new_user_session_path, class: 'btn btn-outline-primary btn-lg' %>
<% end %>

<%# tweet creation form %>
<%= form_with(model: Tweet.new, url: tweets_path) do |f| %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

<%# tweets collection %>
<% Tweet.find_each do |tweet| %>
  <ul>
    <li>
      <%= tweet.body %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>